### ISSUE TITLE
Wanted Aircurve V auto Firmware 

### ISSUE THREAD

**Issue by jimmybbk** [osresearch/airbreak#48]
Hello, I'm just wondering if someone has the Aircurve Vauto firmware. I'm looking to flash my device for sleep apnea treatment. The reason for flashing is im having a real hard time trying to get a machine from the USA to Thailand.

Thanks in advance.

https://tools.usps.com/go/TrackConfirmAction?tLabels=CH096760102US&utm_source=expected&utm_medium=email&utm_content=delivery-options&utm_campaign=trackingnotify

**Comment by osresearch** [comment]
Sorry, we don't have any rights to redistribute the vendor firmware.
