### ISSUE TITLE
AirCurve 10 ASV 401 firmware

### ISSUE THREAD

**Issue by Millstone50** [osresearch/airbreak#61]
Does anyone have this stock firmware in their possession? If so can you leave an email or something where I can get in touch?

**Comment by mtemple** [comment]
Interested as well!

**Comment by dmlerner** [comment]
Unmodified SX567-0401 firmware read off an actual ASV: 

https://drive.google.com/file/d/1AkftFeG2ySBn1yH07WUegWm5Q3COc7oA/view?usp=sharing

**Comment by mtemple** [comment]
Thanks!

**Comment by Millstone50** [comment]
Thank you

**Comment by kqj2354olkjawef984** [comment]
Looks like the comment was deleted - here's a (new) link: https://file.io/EPyfOoyMuFlG

**Comment by EdWorth120** [comment]
Hello @Millstone50 @kqj2354olkjawef984 and @mtemple, does anybody still have that firmware, the present link doesn't work anymore.

**Comment by shaareable** [comment]
I have an ASV however I do not know how to extract the firmware for you.

**Comment by kqj2354olkjawef984** [comment]
ASV 401 firmware: https://fastupload.io/SQSUzsOJ0P9zJyY/file

**Comment by edmundo** [comment]
> ASV 401 firmware: https://fastupload.io/SQSUzsOJ0P9zJyY/file

Thank you

**Comment by EdWorth120** [comment]
> ASV 401 firmware: https://fastupload.io/SQSUzsOJ0P9zJyY/file

Thank you

**Comment by colinoflynn** [comment]
There are no rights to redistribute vendor firmware, please do not ask or use this repository to do so if you want the project to continue to be hosted here.
