### ISSUE TITLE
Aircurve 10 Vauto US firmware  

### ISSUE THREAD

**Issue by zaienk** [osresearch/airbreak#62]
Hello,
I'm looking for the firmware of the Aircurve 10 Vauto US firmware which provides access to the trigger parameter.
If somebody have it and can share it with me.
Thank you

**Comment by EdWorth120** [comment]
Hello @zaienk here is a link: https://file.io/iUANwgVq0Pb1

**Comment by zaienk** [comment]
Thanks a lot !!!


Le lun. 29 janv. 2024, 19:25, EdWorth120 ***@***.***> a
écrit :

**Comment by kqj2354olkjawef984** [comment]
I see the link has been deleted. Care to repost? Here is vauto firmware, without the trigger parameter. https://fastupload.io/yp1SXPNKCu3bYo5/file

**Comment by edmundo** [comment]
> I see the link has been deleted. Care to repost? Here is vauto firmware, without the trigger parameter. https://fastupload.io/yp1SXPNKCu3bYo5/file

This is the link to Vauto version 401 with the trigger parameter: https://fastupload.io/en/To6uZ2TGrwHqjJp/file

**Comment by EdWorth120** [comment]
> I see the link has been deleted. Care to repost? Here is vauto firmware, without the trigger parameter. https://fastupload.io/yp1SXPNKCu3bYo5/file

This is the firmware of Vauto with the trigger parameter enabled: https://fastupload.io/en/To6uZ2TGrwHqjJp/file

**Comment by colinoflynn** [comment]
There are no rights to redistribute vendor firmware, please do not ask or use this repository to do so if you want the project to continue to be hosted here.
